# Generated by Django 4.2.10 on 2024-05-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_teacher_fk_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='fk_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.manager'),
        ),
    ]
