# Generated by Django 4.2.10 on 2024-05-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_teacher_fk_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='fk_manager',
        ),
    ]
