# Generated by Django 4.2.10 on 2024-04-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuizMaker', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmake',
            name='fk_teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.teacher'),
        ),
        migrations.AddField(
            model_name='questions',
            name='fk_quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuizMaker.quizmake'),
        ),
        migrations.AddField(
            model_name='answers',
            name='fk_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QuizMaker.questions'),
        ),
    ]
