# Generated by Django 4.2.10 on 2024-03-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('StudentDoQuiz', '0001_initial'),
        ('QuizMaker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.student'),
        ),
        migrations.AddField(
            model_name='studentdoquiz',
            name='chosen',
            field=models.ManyToManyField(to='StudentDoQuiz.chosenanswer'),
        ),
        migrations.AddField(
            model_name='studentdoquiz',
            name='fk_quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuizMaker.quizmake'),
        ),
        migrations.AddField(
            model_name='studentdoquiz',
            name='fk_student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.student'),
        ),
        migrations.AddField(
            model_name='chosenanswer',
            name='fk_answer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizMaker.answers'),
        ),
        migrations.AddField(
            model_name='chosenanswer',
            name='fk_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizMaker.questions'),
        ),
    ]
