# Generated by Django 4.2.10 on 2024-03-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('no_of_questions', models.IntegerField()),
                ('no_of_quizzes', models.IntegerField()),
                ('no_of_students', models.IntegerField()),
            ],
        ),
    ]
